checkup_price = {"CBC" : "INR 299",
                 "BMP" : "INR 3000",
                 "CMP" : "INR 699",
                 "Thyroid Profile Test" : "INR 299",
                 "LFT" : "INR 370",
                 "Coagulation Panel Test" : "INR 650",
                 "Vitamins and minerals Levels" : "INR 650",
                 "Electrolyte Test" : "INR 299",
                 "Lipid profile" : "INR 500",
                 "Complete Vitamin Panel" : "INR 1650",
                 "chest X-rays" : "INR 300",
                 "Typoid test" : "INR 500",
                 "Malaria test" : "INR 500",
                 "FBS" : "INR 100",
                 "Diabetes Panel Basic" : "INR 480",
                 "Diabetes Profile - Advance" : "INR 999"}